version: "1.0"
services:
  minio:
    image: "quay.io/minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./minio/data1:/data1"
    command: server --console-address ":9001" http://minio/data1
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=root
    healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3
    restart: always