version: '3.1'
services:
  db:
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ~/Database/coshub:/var/lib/postgresql/data
    ports:
      - 5432:5432