version: '3.1'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ~/Database/bocchi:/var/lib/postgresql/data
    ports:
      - 5432:5432
